nyc_parking_violations_2:
  outputs:
    dev:
      type: duckdb
      path: '../data/nyc_parking_violations_2.db'
    prod:
     type: duckdb
     # note that path is slightly different as GitHub actions
     # start in the root directory and not in the
     # nyc_parking_violations directory
     path: '../data/prod_nyc_parking_violations_2.db'  
  target: dev
